services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: ${HOSTNAME_FQDN}
    domainname: ${DOMAIN}
    env_file:
      - ./mail/.env
    environment:
      - OVERRIDE_HOSTNAME=${HOSTNAME_FQDN}
      - POSTMASTER_ADDRESS=postmaster@${DOMAIN}
      - REPORT_RECIPIENT=support@${DOMAIN}
    ports:
      - "25:25"      # SMTP
      - "587:587"    # Submission (STARTTLS)
      - "993:993"    # IMAPS
    volumes:
      - ./mail/mail-data/:/var/mail/
      - ./mail/mail-state/:/var/mail-state/
      - ./mail/mail-logs/:/var/log/mail/
      - ./mail/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped
    stop_grace_period: 1m
    cap_add: [ "NET_ADMIN" ]
    healthcheck:
      test: "ss --listening --ipv4 --tcp | grep --silent ':smtp' || exit 1"
      timeout: 3s
      retries: 0
    networks:
      mailnet:
        aliases: [ "mail", "${HOSTNAME_FQDN}" ]

networks:
  mailnet:
    driver: bridge
