services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROLE: api
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./files:/app/files
    depends_on:
      - redis

  worker-ocr:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROLE: ocr
    env_file: .env
    volumes:
      - ./files:/app/files
    depends_on:
      - redis

  worker-nlp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROLE: nlp
    env_file: .env
    volumes:
      - ./files:/app/files
    depends_on:
      - redis

  crawler:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROLE: crawler
    env_file: .env
    volumes:
      - ./files:/app/files

  watcher:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROLE: watcher
    env_file: .env
    volumes:
      - ./files:/app/files

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
